apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: $roleBindingName
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: $roleBindingRoleType
  name: $roleBindingRoleName
subjects:
- kind: ServiceAccount
  name: $roleBindingSubjectName
  namespace: $roleBindingSubjectNamespace
