apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: $roleBindingName
  namespace: $roleBindingNamespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: $roleBindingRoleType
  name: $roleBindingRoleName
subjects:
- kind: ServiceAccount
  name: $roleBindingSubjectName
  namespace: $roleBindingSubjectNamespace
